spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# HS256 ????? ??? ??? ??? 256bit, ? 32byte ??? secret key? ???? ??.
# Base64 ? ???? ? ??
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
